name: car_parking
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: http://ondart.me/
version: 0.1.0
description: >
  A game in Dart with a model based on the Rush Hour game.
dependencies:
  browser: any
